version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/code
  # ports:
  #   - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
     - data:/var/lib/postgresql/data

volumes:
  data:
    driver: "local"
